[package]
authors = ["Petr Horáček <hrck@protonmail.com>"]
name = "proton-instruments-karplus-strong-music-box"
version = "0.4.0" # hack/release.sh
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/zlosynth/proton"
readme = "../README.md"
publish = false
